name: Cowsay CI

on:
  push:
    branches:
      - main

jobs:
  build_test_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t cowsay-app:latest .

    - name: Run Docker container
      run: docker run -d -p 8080:8080 cowsay-app:latest

    - name: Wait for server
      run: sleep 5

    - name: Test app with curl
      run: curl http://localhost:8080

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag Docker image
      run: docker tag cowsay-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/cowsay-app:latest

    - name: Push Docker image to DockerHub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/cowsay-app:latest


